name: build
on:
  push:
    branches:
      - "master"
jobs:
  build:
    env:
      FIREBASE_TOKEN: ${{ secrets.GCLOUD_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm i && npm i -g firebase-tools
      - name: building
        run: npm run build:all
      - name: deploy
        run: npm run deploy --token ${{ secrets.GCLOUD_TOKEN }}
