name: deploy
on:
  push:
    branches:
      - "master"
  # workflow_run:
  #   workflows:
  #     - "check linter"
  #   branches: [master]
  #   types:
  #     - "completed"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.GCLOUD_TOKEN }}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use node
        run: node -v
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm i && npm i -g firebase-tools
      - name: building
        run: npm run build
      - name: deploy
        run: firebase deploy --token ${{ secrets.GCLOUD_TOKEN }}
