name: check linter
on: push
jobs:
  check-linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Use node
        run: node -v
      - uses: actions/checkout@v2
      - name: installing typescript
        run: npm i -g typescript
      - name: check linter api
        run: cd api && npm i && npm run lint
      - name: check linter app
        run: cd app && npm i && npm run lint
